# Generated by Django 5.2.1 on 2025-07-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionstats',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
        migrations.AddField(
            model_name='admissionstats',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.academicsession'),
        ),
    ]
