# Generated by Django 5.2.1 on 2025-07-04 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('programs', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionletter',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_admission_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.academicsession'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationapproved',
            name='approved_app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationapproved',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionletter',
            name='approved_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_letter', to='applications.applicationapproved'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.applicationstatus'),
        ),
        migrations.AddField(
            model_name='applicationtracking',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationtracking',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationtracking',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.applicationstatus'),
        ),
    ]
